### ISSUE TITLE
What country is closest to me? Ceuta and Melilla missing

### ISSUE THREAD

**Issue by Robot8A** [tjukanovt/tjukanovt.github.io#3]
What country is closest to me? Ceuta and Melilla missing as part of Spain, so parts of Morocco are displayed wrongly as closer to UK (Gib.) or Algeria.

**Comment by tjukanovt** [comment]
Thanks for reporting. This is a scale issue: a lot of other small parts are missing too, but to keep the computation time of the analysis somewhat sensible these issues appear and I have generelaized the Natural Earth data a bit.
